accounts:
  - name: alice
    coins: ["200000000uheart"]
  - name: x4139
    coins: [ "400000000uheart" ]
    address: "humans1jxadxcgfjzda0hqlh550rf278cxpet7fh8gezv"
  - name: bob
    coins: ["100000000uheart"]
validator:
  name: alice
  staked: "100000000uheart"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000uheart"]
genesis:
  app_state:
    bank:
      denom_metadata:
        - description: "Humans ai HEART"
          display: "heart"
          base: "uheart"
          name: "Humans"
          symbol: "HEART"
          denom_units:
            - denom: "uheart"
              aliases:
                - "milliheart"
              exponent: "0"
            - denom: "heart"
              exponent: "6"
    staking:
      params:
        bond_denom: "uheart"
      exported: false
    gov:
      starting_proposal_id: '1'
    mint:
      params:
        mint_denom: "uheart"